#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;

const string YES = "Yes";
const string NO = "No";

void solve(long long a, long long b, long long c, long long d, long long e, long long f, long long g, long long h, long long i, long long j, long long k, long long l){

}

// Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long a;
    std::scanf("%lld", &a);
    long long b;
    std::scanf("%lld", &b);
    long long c;
    std::scanf("%lld", &c);
    long long d;
    std::scanf("%lld", &d);
    long long e;
    std::scanf("%lld", &e);
    long long f;
    std::scanf("%lld", &f);
    long long g;
    std::scanf("%lld", &g);
    long long h;
    std::scanf("%lld", &h);
    long long i;
    std::scanf("%lld", &i);
    long long j;
    std::scanf("%lld", &j);
    long long k;
    std::scanf("%lld", &k);
    long long l;
    std::scanf("%lld", &l);
    solve(a, b, c, d, e, f, g, h, i, j, k, l);
    return 0;
}
