#include <bits/stdc++.h>

#include <algorithm>
#include <atcoder/all>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>

using namespace std;
using namespace atcoder;

// clang-format off
/* accelration */
// 高速バイナリ生成
#pragma GCC optimize("O3")
#pragma GCC optimize("unroll-loops")

// cin cout の結びつけ解除, stdioと同期しない(入出力非同期化)
// cとstdの入出力を混在させるとバグるので注意
struct Fast {
    Fast() {
        std::cin.tie(0);
        ios::sync_with_stdio(false);
    }
} fast;

/* alias */
using ull = unsigned long long;
using ll = long long;
using vi = vector<int>;
using vl = vector<long>;
using vll = vector<long long>;
using vvi = vector<vi>;
using vvl = vector<vl>;
using vvll = vector<vll>;
using vs = vector<string>;
using pii = pair<int, int>;

/* define short */
#define pb push_back
#define mp make_pair
#define all(obj) (obj).begin(), (obj).end()
#define YESNO(bool) if(bool){cout<<"YES"<<endl;}else{cout<<"NO"<<endl;}
#define yesno(bool) if(bool){cout<<"yes"<<endl;}else{cout<<"no"<<endl;}
#define YesNo(bool) if(bool){cout<<"Yes"<<endl;}else{cout<<"No"<<endl;}

/* REP macro */
#define reps(i, a, n) for (ll i = (a); i < (ll)(n); ++i)
#define rep(i, n) reps(i, 0, n)
#define rrep(i, n) reps(i, 1, n + 1)
#define repd(i, n) for(ll i=n-1;i>=0;i--)
#define rrepd(i, n) for(ll i=n;i>=1;i--)

/* debug */
// 標準エラー出力を含む提出はrejectされる場合もあるので注意
#define debug(x) cerr << "\033[33m(line:" << __LINE__ << ") " << #x << ": " << x << "\033[m" << endl;

// search_length: 走査するベクトル長の上限(先頭から何要素目までを検索対象とするか、1始まりで)
template<typename T>
inline bool vector_finder(std::vector<T> vec, T element, unsigned int search_length) {
    auto itr = std::find(vec.begin(), vec.end(), element);
    size_t index = std::distance(vec.begin(), itr);
    if (index == vec.size() || index >= search_length) { return false; } else { return true; }
}

template<typename T>
inline void print(const vector<T> &v, string s = " ") {
    rep(i, v.size()) cout << v[i] << (i != (ll) v.size() - 1 ? s : "\n");
}

template<typename T, typename S>
inline void print(const pair<T, S> &p) { cout << p.first << " " << p.second << endl; }

template<typename T>
inline void print(const T &x) { cout << x << "\n"; }

template<typename T, typename S>
inline void print(const vector<pair<T, S>> &v) { for (auto &&p: v) print(p); }

// 第一引数と第二引数を比較し、第一引数(a)をより大きい/小さい値に上書き
template<typename T>
inline bool chmin(T &a, const T &b) {
    bool compare = a > b;
    if (a > b) a = b;
    return compare;
}

template<typename T>
inline bool chmax(T &a, const T &b) {
    bool compare = a < b;
    if (a < b) a = b;
    return compare;
}

const ll INF = 1e18;
// clang-format on
map<ll, ll, greater<ll>> e() {
    map<ll, ll, greater<ll>> a;
    return a;
}

map<ll, ll, greater<ll>> op(map<ll, ll, greater<ll>> x,
                            map<ll, ll, greater<ll>> y) {
    for (pair<ll, ll> z : y) {
        x[z.first] += z.second;
    }
    map<ll, ll, greater<ll>> ret;
    ll q = 0;
    for (pair<ll, ll> z : x) {
        q++;
        if (q > 2) {
            break;
        }
        ret[z.first] = z.second;
    }

    return ret;
}

// Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips:
// You use the default template now. You can remove this line by using your
// custom template)
int main() {
    ll N, Q;
    cin >> N >> Q;
    vll A(N);
    segtree<map<ll, ll, greater<ll>>, op, e> seg(N);
    rep(i, N) {
        cin >> A[i];
        map<ll, ll, greater<ll>> a;
        a[A[i]] = 1;
        seg.set(i, a);
    }

    // rep(i, N) {
    //     map<ll, ll> a = seg.get(i);
    //     for (pair<ll, ll> z : a) {
    //         cout << z.first << ":" << z.second << endl;
    //     }
    // }
    // map<ll, ll, greater<ll>> b = seg.all_prod();
    // for (pair<ll, ll> z : b) {
    //     cout << z.first << ":" << z.second << endl;
    // }

    rep(i, Q) {
        ll X, Y, Z;
        cin >> X >> Y >> Z;
        if (X == 1) {
            map<ll, ll, greater<ll>> a;
            a[Z] = 1;
            seg.set(Y - 1, a);
        } else {
            map<ll, ll, greater<ll>> t = seg.prod(Y - 1, Z);
            // cout << " " << t.size() << endl;
            // cout << t.rbegin()->first << endl;
            // cout << t.rbegin()->second << endl;
            if (t.size() <= 1) {
                cout << 0 << endl;
            } else {
                // cout << t.rbegin()->first << endl;
                cout << t.rbegin()->second << endl;
            }
        }
    }

    // Failed to predict input format
    return 0;
}
