#include <atcoder/all>
#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
#include <bits/stdc++.h>

using namespace std;
using namespace atcoder;

// clang-format off
/* accelration */
// 高速バイナリ生成

#pragma GCC optimize("O3")
#pragma GCC optimize("unroll-loops")

// cin cout の結びつけ解除, stdioと同期しない(入出力非同期化)
// cとstdの入出力を混在させるとバグるので注意
struct Fast {
    Fast() {
        std::cin.tie(0);
        ios::sync_with_stdio(false);
    }
} fast;

/* alias */
using ull = unsigned long long;
using ll = long long;
using vi = vector<int>;
using vl = vector<long>;
using vll = vector<long long>;
using vvi = vector<vi>;
using vvl = vector<vl>;
using vvll = vector<vll>;
using vs = vector<string>;
using pii = pair<int, int>;

/* define short */
#define pb push_back
#define mp make_pair
#define all(obj) (obj).begin(), (obj).end()
#define YESNO(bool) if(bool){cout<<"YES"<<endl;}else{cout<<"NO"<<endl;}
#define yesno(bool) if(bool){cout<<"yes"<<endl;}else{cout<<"no"<<endl;}
#define YesNo(bool) if(bool){cout<<"Yes"<<endl;}else{cout<<"No"<<endl;}

/* REP macro */
#define reps(i, a, n) for (ll i = (a); i < (ll)(n); ++i)
#define rep(i, n) reps(i, 0, n)
#define rrep(i, n) reps(i, 1, n + 1)
#define repd(i, n) for(ll i=n-1;i>=0;i--)
#define rrepd(i, n) for(ll i=n;i>=1;i--)

/* debug */
// 標準エラー出力を含む提出はrejectされる場合もあるので注意
#define debug(x) cerr << "\033[33m(line:" << __LINE__ << ") " << #x << ": " << x << "\033[m" << endl;

// search_length: 走査するベクトル長の上限(先頭から何要素目までを検索対象とするか、1始まりで)
template<typename T>
inline bool vector_finder(std::vector<T> vec, T element, unsigned int search_length) {
    auto itr = std::find(vec.begin(), vec.end(), element);
    size_t index = std::distance(vec.begin(), itr);
    if (index == vec.size() || index >= search_length) { return false; } else { return true; }
}

template<typename T>
inline void print(const vector<T> &v, string s = " ") {
    rep(i, v.size()) cout << v[i] << (i != (ll) v.size() - 1 ? s : "\n");
}

template<typename T, typename S>
inline void print(const pair<T, S> &p) { cout << p.first << " " << p.second << endl; }

template<typename T>
inline void print(const T &x) { cout << x << "\n"; }

template<typename T, typename S>
inline void print(const vector<pair<T, S>> &v) { for (auto &&p: v) print(p); }

// 第一引数と第二引数を比較し、第一引数(a)をより大きい/小さい値に上書き
template<typename T>
inline bool chmin(T &a, const T &b) {
    bool compare = a > b;
    if (a > b) a = b;
    return compare;
}

template<typename T>
inline bool chmax(T &a, const T &b) {
    bool compare = a < b;
    if (a < b) a = b;
    return compare;
}


void solve(long long N, long long M, std::vector<long long> A, std::vector<long long> B, std::vector<long long> C) {
    std::cout << std::fixed << std::setprecision(10);
    vector<vector<tuple<ll, ll, ll>>> x(N + 1);
    rep(i, M) {
        x[A[i]].pb(make_tuple(B[i], C[i], i + 1));
        x[B[i]].pb(make_tuple(A[i], C[i], i + 1));
    }
//    rep(i, x.size()) {
//        rep(j, x[i].size()) {
//            cout << i << " " << get<0>(x[i][j]) << " " << get<2>(x[i][j]) << endl;
//        }
//    }
    vll l(N + 1, LLONG_MAX);
    l[0] = 0;
    l[1] = 0;
    vvll s = {{1}};
    vll ss = {1};
    ll min = 0;
    ll ii = 0;
    ll max = LLONG_MAX;
    vll ret(N + 1);
    while (max > min && !s[ii].empty()) {
        min = LLONG_MAX;
        rep(i, s[ii].size()) {
            rep(j, x[s[ii][i]].size()) {
//                cout << l[get<0>(x[s[ii][i]][j])] << " " << l[s[ii][i]] + get<1>(x[s[ii][i]][j]) << endl;
                if (l[get<0>(x[s[ii][i]][j])] > l[s[ii][i]] + get<1>(x[s[ii][i]][j])) {
                    s.resize(ii + 2);
                    s[ii + 1].pb(get<0>(x[s[ii][i]][j]));
                    l[get<0>(x[s[ii][i]][j])] = l[s[ii][i]] + get<1>(x[s[ii][i]][j]);
                    ret[get<0>(x[s[ii][i]][j])] = get<2>(x[s[ii][i]][j]);
                    if (min > l[get<0>(x[s[ii][i]][j])]) {
                        min = l[get<0>(x[s[ii][i]][j])];
                    }
                }
            }
        }
//        cout << "min: " << min << endl;
        max = 0;
        rep(i, l.size()) {
            if (max < l[i]) {
                max = l[i];
            }
        }
//        cout << "max: " << max << endl;
        ii++;
    }
    reps(i, 2, N + 1) {
        if (i != 2) {
            cout << " ";
        }
        cout << ret[i];
    }
    cout << endl;
//    ll d = 0;
//    rep(i, l.size()) {
//        d += l[i];
//    }
//    cout << d << endl;
}

// Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main() {
    long long N;
    cin >> N;
    long long M;
    cin >> M;
    std::vector<long long> A(M);
    std::vector<long long> B(M);
    std::vector<long long> C(M);
    for (int i = 0; i < M; i++) {
        cin >> A[i];
        cin >> B[i];
        cin >> C[i];
    }
    solve(N, M, std::move(A), std::move(B), std::move(C));
    return 0;
}
